website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/Login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash(f'Welcome back, {user.user_name}!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect', category='error')
        else:
            flash('Email not found.', category='error')
    return render_template('login.html', user=current_user)

@auth.route('/SignUp', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        user_name = request.form.get('userName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        existing_user = User.query.filter_by(user_name=user_name).first()

        if user:
            flash('Looks like you already have an account.', category='error')
        elif existing_user and existing_user.email != email:
            flash('Username already exists. Please choose a different one.', 'error')
        elif ' ' in user_name:
            flash('Username cannot conain spaces.', category='error')
        elif ' ' in password1:
            flash('Password cannot contain spaces.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 charachters.', category='error')
        elif not user_name.strip():
            flash('Please enter a username.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        elif len(password1) < 7 or len(password1) > 15:
            flash('Password must be between 7 and 15 characters.', category='error')
        else:
            new_user = User(email=email, user_name=user_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('sign_up.html', user=current_user)

@auth.route('/Edit', methods=['GET', 'POST'])
@login_required
def edit_account():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')

        existing_user = User.query.filter_by(user_name=name).first()

        if existing_user and existing_user.email != email:
            flash('Username already exists. Please choose a different one.', 'error')
            return render_template('edit_account.html', user=current_user)
        elif not name.strip():
            flash('You have to enter a username.', category='error')
        elif ' ' in name:
            flash('Username cannot contain spaces.', category='error')
        else:
            user = User.query.filter_by(email=email).first()
            user.user_name = name
            user.email = email
            db.session.commit()
            flash('Account updated successfully!', 'success')
            return redirect(url_for('views.account'))

    return render_template('edit_account.html', user=current_user)

@auth.route('/ChangePassword', methods=['GET', 'POST'])
@login_required
def changePassword():
    if request.method == 'POST':
        email = request.form.get('email')
        cur_pass = request.form.get('current_password')
        password = request.form.get('new_password')
        conf_pass = request.form.get('conf_new_password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if not password.strip():  # Check if password is blank or only contains spaces
                flash('You cannot leave password field blank.', category='error')
            elif ' ' in password:  # Check if password contains spaces
                flash('Password cannot contain spaces.', category='error')
            elif len(password) < 7 or len(password) > 15:
                flash('Password must be between 7 and 15 characters.', category='error')
            elif not cur_pass:
                flash('Please enter your current password.', category='error')
            elif conf_pass != password:
                flash('Passwords do not match. Please try again.', category='error')
            else:
                if check_password_hash(user.password, cur_pass):
                    new_password_hash = generate_password_hash(password, method='sha256')
                    user.password = new_password_hash
                    db.session.commit()
                    flash('Password successfully changed!', category='success')
                    return redirect(url_for('views.account'))
                else:
                    flash('Invalid current password. Please try again.', category='error')
        else:
            flash('Invalid email. Please try again.', category='error')

    return render_template('change_password.html', user=current_user)


@auth.route('/Logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/DeleteAccount', methods=['GET', 'POST'])
@login_required
def remove_account():
    if request.method == 'POST':
        User.query.filter(User.id == current_user.id).delete()
        db.session.commit()
        logout_user()
        flash('Account Deleted.', category='error')
        return redirect(url_for('auth.login'))
    else:
        flash('Once your account is deleted, it cannot be undone.', category='error')
    return render_template('remove_acct.html', user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from . import db, forsale
from .models import Product

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    products = Product.query.all()
    return render_template('home.html', user=current_user, products=products)

@views.route('/About', methods=['GET', 'POST'])
def about():
    return render_template('about.html', user=current_user)

@views.route('/Cart', methods=['GET', 'POST'])
@login_required
def cart():
    return render_template('cart.html', user=current_user)

@views.route('/Account', methods=['GET', 'POST'])
@login_required
def account():
    return render_template('acct_details.html', user=current_user)

@views.route('/ContactUs', methods=['GET', 'POST'])
@login_required
def contact():
    return render_template('contact.html', user=current_user)

website/templates/about.html
{% extends "base.html" %} 
{% block title %}About{% endblock %} 

{% block content %}

<div class="home-welcome">
    <div class="photo">
        <div class="author">

        </div>
    </div>
    <div class="message">
        <p>Hello, My name is Anthony.</p>
    </div>
</div>

{% endblock %}

website/templates/acct_details.html
{% extends "base.html" %}
{% block title %}Account{% endblock %}
{% block content %}
<div class="container">
<br>
<div id="act-details" class="form-bubble">
<h1 style="text-align: center;">{{ user.user_name }}</h1><hr>
<h4>Email:</h4>
<h6>{{ user.email }}</h6>
<h4>Username:</h4>
<h6>{{ user.user_name }}</h6>
<a id="edit_user" class="btn btn-primary" href="{{url_for('auth.edit_account')}}">Edit Username</a>
<a id="change_pass" class="btn btn-primary" href="{{url_for('auth.changePassword')}}">Change Password</a>
</div>
</div>
{% endblock %}

website/templates/addproduct.html
{% extends "base.html" %} 
{% block title %}About{% endblock %} 

{% block content %}

{% if user.email == 'admin@auth.com' %}
<div class="container">
    <br>
    <div class="form-bubble">
      <form method="POST" enctype="multipart/form-data">
        <h3 align="center">Add Product</h3>
        <div class="form-group">
            <label for="image">Image:</label><br>
            <input
              type="file"
              id="image"
              name="image"
            />
          </div>
        <div class="form-group">
          <label for="name">Name</label>
          <input
            type="text"
            class="form-control"
            id="name"
            name="name"
            placeholder="Product Name"
          />
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <input
            type="text"
            class="form-control"
            id="description"
            name="description"
            placeholder="Product Description"
          />
        </div>
        <div class="form-group">
          <label for="price">Price</label>
          <input
            type="number"
            class="form-control"
            id="price"
            name="price"
            placeholder="20"
          />
        </div>
        <hr>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-success"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1.2em" width="1.2em" xmlns="http://www.w3.org/2000/svg"><path d="M480 580H372a8 8 0 0 0-8 8v48a8 8 0 0 0 8 8h108v108a8 8 0 0 0 8 8h48a8 8 0 0 0 8-8V644h108a8 8 0 0 0 8-8v-48a8 8 0 0 0-8-8H544V472a8 8 0 0 0-8-8h-48a8 8 0 0 0-8 8v108zm374.6-291.3c6 6 9.4 14.1 9.4 22.6V928c0 17.7-14.3 32-32 32H192c-17.7 0-32-14.3-32-32V96c0-17.7 14.3-32 32-32h424.7c8.5 0 16.7 3.4 22.7 9.4l215.2 215.3zM790.2 326L602 137.8V326h188.2z"></path></svg>Add Product</button>
      </form>
    </div>
    </div>
{% endif %}

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/base.css')}}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{{url_for('views.home')}}">Belinda's Crafts</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{{url_for('views.about')}}">About</a>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 014.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 01-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 011.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 012.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 012.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 011.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 01-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 018.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 001.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 00.52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 00-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 00-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 00-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 00-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 00.52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 001.255-.52l.094-.319z" clip-rule="evenodd"></path><path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"></path></svg> Settings
          </a>
          <div style="padding: 2px;" class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if user.email == 'admin@auth.com' %}
            <a class="drowdown-item btn btn-success" href="{{url_for('add_product.addproduct')}}"><svg style="margin-bottom: 1px;" stroke="currentColor" fill="currentColor" stroke-width="0" t="1551322312294" viewBox="0 0 1024 1024" version="1.1" pId="10297" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg"><defs></defs><path d="M474 152m8 0l60 0q8 0 8 8l0 704q0 8-8 8l-60 0q-8 0-8-8l0-704q0-8 8-8Z" pId="10298"></path><path d="M168 474m8 0l672 0q8 0 8 8l0 60q0 8-8 8l-672 0q-8 0-8-8l0-60q0-8 8-8Z" pId="10299"></path></svg>Add Product</a>
          {% endif %}
            <a class="dropdown-item" href="{{url_for('views.account')}}"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M880 112H144c-17.7 0-32 14.3-32 32v736c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V144c0-17.7-14.3-32-32-32zm-40 728H184V184h656v656zM492 400h184c4.4 0 8-3.6 8-8v-48c0-4.4-3.6-8-8-8H492c-4.4 0-8 3.6-8 8v48c0 4.4 3.6 8 8 8zm0 144h184c4.4 0 8-3.6 8-8v-48c0-4.4-3.6-8-8-8H492c-4.4 0-8 3.6-8 8v48c0 4.4 3.6 8 8 8zm0 144h184c4.4 0 8-3.6 8-8v-48c0-4.4-3.6-8-8-8H492c-4.4 0-8 3.6-8 8v48c0 4.4 3.6 8 8 8zM340 368a40 40 0 1 0 80 0 40 40 0 1 0-80 0zm0 144a40 40 0 1 0 80 0 40 40 0 1 0-80 0zm0 144a40 40 0 1 0 80 0 40 40 0 1 0-80 0z"></path></svg> Account Details</a>
            <a class="dropdown-item" href="{{url_for('views.contact')}}"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M20,4H6C4.897,4,4,4.897,4,6v5h2V8l6.4,4.8c0.178,0.133,0.389,0.2,0.6,0.2s0.422-0.067,0.6-0.2L20,8v9h-8v2h8 c1.103,0,2-0.897,2-2V6C22,4.897,21.103,4,20,4z M13,10.75L6.666,6h12.668L13,10.75z"></path><path d="M2 12H9V14H2zM4 15H10V17H4zM7 18H11V20H7z"></path></svg> Contact Us</a>
            <a class="dropdown-item" id="logout" href="{{url_for('auth.logout')}}"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M312 372c-7.7 0-14 6.3-14 14 0 9.9-8.1 18-18 18H94c-9.9 0-18-8.1-18-18V126c0-9.9 8.1-18 18-18h186c9.9 0 18 8.1 18 18 0 7.7 6.3 14 14 14s14-6.3 14-14c0-25.4-20.6-46-46-46H94c-25.4 0-46 20.6-46 46v260c0 25.4 20.6 46 46 46h186c25.4 0 46-20.6 46-46 0-7.7-6.3-14-14-14z"></path><path d="M372.9 158.1c-2.6-2.6-6.1-4.1-9.9-4.1-3.7 0-7.3 1.4-9.9 4.1-5.5 5.5-5.5 14.3 0 19.8l65.2 64.2H162c-7.7 0-14 6.3-14 14s6.3 14 14 14h256.6L355 334.2c-5.4 5.4-5.4 14.3 0 19.8l.1.1c2.7 2.5 6.2 3.9 9.8 3.9 3.8 0 7.3-1.4 9.9-4.1l82.6-82.4c4.3-4.3 6.5-9.3 6.5-14.7 0-5.3-2.3-10.3-6.5-14.5l-84.5-84.2z"></path></svg> Logout</a>
            {% if user.email != 'admin@auth.com' %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item btn btn-danger" id="deleteacct" href="{{url_for('auth.remove_account')}}"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"></path><path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"></path></svg> Delete Account</a>
          </div>
            {% endif %}
        </li>
        {% if user.email != 'admin@auth.com' %}
        <a class="nav-item nav-link" id="profile" href="{{url_for('views.cart')}}"><svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg"><path d="M922.9 701.9H327.4l29.9-60.9 496.8-.9c16.8 0 31.2-12 34.2-28.6l68.8-385.1c1.8-10.1-.9-20.5-7.5-28.4a34.99 34.99 0 0 0-26.6-12.5l-632-2.1-5.4-25.4c-3.4-16.2-18-28-34.6-28H96.5a35.3 35.3 0 1 0 0 70.6h125.9L246 312.8l58.1 281.3-74.8 122.1a34.96 34.96 0 0 0-3 36.8c6 11.9 18.1 19.4 31.5 19.4h62.8a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7h161.1a102.43 102.43 0 0 0-20.6 61.7c0 56.6 46 102.6 102.6 102.6s102.6-46 102.6-102.6c0-22.3-7.4-44-20.6-61.7H923c19.4 0 35.3-15.8 35.3-35.3a35.42 35.42 0 0 0-35.4-35.2zM305.7 253l575.8 1.9-56.4 315.8-452.3.8L305.7 253zm96.9 612.7c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6zm325.1 0c-17.4 0-31.6-14.2-31.6-31.6 0-17.4 14.2-31.6 31.6-31.6s31.6 14.2 31.6 31.6a31.6 31.6 0 0 1-31.6 31.6z"></path></svg></a>
        {% endif %}
        {% if user.email == 'admin@auth.com' %}
          <a class="nav-item nav-link disabled" style="color: gold; font-weight: 400;">{{ user.user_name }}</a>
        {% endif %}
        {% else %}
        <a class="nav-item nav-link" id="login" href="/Login">Login</a>
        <a class="nav-item nav-link" id="signUp" href="/SignUp">Sign Up</a>
        {% endif %}
        </div>
      </div>
    </nav>


    
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div>{% block content %} {% endblock %}</div>
    <script>
      document.querySelectorAll('.add-to-cart').forEach(button => {
          button.addEventListener('click', function(event) {
              event.preventDefault();
              const productId = this.dataset.productId;
              fetch(`/add_to_cart/${productId}`, {
                  method: 'POST',
                  headers: {
                      'Content-Type': 'application/json',
                      'X-CSRFToken': '{{ csrf_token() }}'  <!-- Ensure csrf_token is passed here -->
                  }
              })
              .then(response => {
                  if (response.ok) {
                      console.log('Product added to cart');
                      location.reload();
                  } else {
                      console.error('Failed to add product to cart');
                  }
              })
              .catch(error => console.error('Error:', error));
          });
      });
      </script>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/cart.html
{% extends "base.html" %}
{% block title %}Shopping Cart{% endblock %}

{% block content %}
<div class="container">
<h1 style="text-align: center;">{{ user.user_name }}</h1><hr>
</div>
{% endblock %}

website/templates/change_password.html
{% extends "base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
<div class="container">
<br>
<div class="form-bubble">
<form method="POST">
    <h3 align="center">Change Password</h3><hr>
    <div class="form-group">
        <input type="hidden" name="id" value="{{ user.id }}">
    </div>
    <div class="form-group">
        <label hidden for="email">Email Address</label>
        <input hidden
          type="email"
          class="form-control"
          id="email"
          name="email"
          value="{{ user.email }}"
        />
      </div>
      <div class="form-group">
        <label for="new_password">Current Password:</label>
        <input
          type="password"
          class="form-control"
          id="current_password"
          name="current_password"
          placeholder="Enter current password"
        />
      </div>
    <div class="form-group">
        <label for="new_password">New Password:</label>
        <input
          type="password"
          class="form-control"
          id="new_password"
          name="new_password"
          placeholder="Enter new password"
        />
      </div>
      <div class="form-group">
        <label for="conf_new_password">Confirm New Password:</label>
        <input
          type="password"
          class="form-control"
          id="conf_new_password"
          name="conf_new_password"
          placeholder="Confirm New Password"
        />
      </div>
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <button type="submit" class="btn btn-success">Login</button>
</form>
</div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <div class="container">
    <br>
    <div class="form-bubble">
      <form method="POST">
        <h3 align="center">Login</h3>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter email"
          />
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter password"
          />
        </div>
        <hr>
        <p>Don't have an account? <a href="{{url_for('auth.sign_up')}}">Sign Up</a></p>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-success">Login</button>
      </form>
    </div>
    </div>
    {% endblock %}

website/templates/remove_acct.html
{% extends "base.html" %}
{% block title %}Delete Account{% endblock %}

{% block content %}
<br>
<div class="container">
<div class="form-bubble">
<h1 style="text-align: center;">Delete Your Account</h1>
<hr>
<div class="delete-account">
    <p>Are you sure you want to delete your account? Once you click the Delete Account button, your account will be deleted and will not be recovered.</p>
    <form method="POST">
    <button style="text-align: center;" type="submit" class="btn btn-danger">Delete Account</button>
    </form>
</div>
</div>
</div>
{% endblock %}